# Generated by Django 5.1.2 on 2024-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountphoto',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountphoto',
            name='user_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
